PlayaLinda/Controllers/BasicController.cs
using ENTIDAD;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Internal;
using Microsoft.Extensions.FileProviders;
using System;
using System.IO;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace PlayaLinda.Controllers
{
    public class BasicController : Controller
    {

        NEGOCIO.FacilidadesCapaNegocio FacilidadesCapaNegocio = new NEGOCIO.FacilidadesCapaNegocio();
        NEGOCIO.HabitacionCapaNegocio HabitacionesCapaNegocio = new NEGOCIO.HabitacionCapaNegocio();
     

        public ActionResult Facilidades()
        {
            ENTIDAD.Facilidades tipo = new ENTIDAD.Facilidades();
            //ViewData["listaTipoHabitaciones"] = habitacionCapaNegocio.listadoTipoHabitaciones();
            return View(FacilidadesCapaNegocio.listadoFacilidades());
        }

       

        public ActionResult Tarifas()
        {
            return View(HabitacionesCapaNegocio.listadoTipoHabitaciones());
        }


    }
}

PlayaLinda/Controllers/ContenidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlayaLinda.Controllers
{
    public class ContenidoController : Controller
    {
        // GET: Contenido
        NEGOCIO.ContenidoCapaNegocio capaNegocios = new NEGOCIO.ContenidoCapaNegocio();
        NEGOCIO.ImagenCapaNegocio img = new NEGOCIO.ImagenCapaNegocio();
        NEGOCIO.PromocionCapaNegocio promocionCapaNegocio = new NEGOCIO.PromocionCapaNegocio();
        public ActionResult Contacto()
        {

            ViewData["contenidoVista"] = capaNegocios.listadoContenido(new ENTIDAD.Contenido(2));
            return View();
        }


        public ActionResult Nosotros()
        {

            ViewData["contenidoVista"] = capaNegocios.listadoContenido(new ENTIDAD.Contenido(1));
            return View(img.listadoImagenes());
        }


        public ActionResult Inicio()
        { 

            ViewData["listadoPromociones"] = promocionCapaNegocio.listadoPromociones();
            ViewData["contenidoVista"] = capaNegocios.listadoContenido(new ENTIDAD.Contenido(4));
            return View();
        }
    }
}

PlayaLinda/Controllers/MapaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlayaLinda.Controllers
{
    public class MapaController : Controller
    {
        // GET: Mapa

        NEGOCIO.MapaCapaNegocio capaNegocios = new NEGOCIO.MapaCapaNegocio();
        NEGOCIO.ContenidoCapaNegocio contenido = new NEGOCIO.ContenidoCapaNegocio();
        public ViewResult Mapa(string lat, string lng)
        {
            ENTIDAD.Mapa mapa = new ENTIDAD.Mapa(); mapa.latitudOrigen = lat; mapa.longitudOrigen = lng;
            ViewData["contenidoVista"] = contenido.listadoContenido(new ENTIDAD.Contenido(3));
            capaNegocios.modificarCoordenadasOrigen(mapa);
            return View(capaNegocios.listadoCoordenadasOrigen());

        }

        public ActionResult Llegar()
        {
            return View();
        }
    }
}

PlayaLinda/Controllers/ReservaController.cs
using ENTIDAD;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlayaLinda.Controllers
{
    public class ReservaController : Controller
    {

        NEGOCIO.ReservacionCapaNegocios reservacionCapaNegocios = new NEGOCIO.ReservacionCapaNegocios();
        NEGOCIO.HabitacionCapaNegocio HabitacionesCapaNegocio = new NEGOCIO.HabitacionCapaNegocio();
        NEGOCIO.ClienteCapaNegocio clienteCapaNegocio = new NEGOCIO.ClienteCapaNegocio();

        public ActionResult ReservaLinea(Reservacion reservacion) {

            ViewBag.mensaje = "Habitación disponible para ser reservada"+ reservacion.codigoHabitacion;
            return View();
        }
        

        public ActionResult Reservar()
        {
            return View(HabitacionesCapaNegocio.listadoTipoHabitaciones());
        }
      
        public ActionResult Estado(Reservacion reservacion)
        {

            if (reservacionCapaNegocios.verificarReservacion(reservacion) > 0)
            {
                ViewBag.mensaje = "Lo sentimos, el rango de fechas que seleccionaste se encuentran ocupadas. En este calendario podrás ver que fechas se encuentran disponibles";
                return View(reservacionCapaNegocios.sugerirReservacion());
            }
            else
            {
                ViewData["idHabitacion"] = reservacion.codigoHabitacion;
                ViewData["fechaInicio"] = reservacion.fechaLlegada;
                ViewData["fechaFin"] = reservacion.fechaSalida;
                ViewBag.mensaje = "Habitación disponible para ser reservada";
                return View("ReservaLinea");
            }  
        }

        
        public ActionResult ListaReservaciones()
        {
            return View(reservacionCapaNegocios.listarReservaciones());
        }

        public ActionResult ConsultarReservacion(int codigoReservacion) {

            return View(reservacionCapaNegocios.consultarReservaciones(new Reservacion(codigoReservacion)));
        }

        public ActionResult DatosUsuario (string codigoHabitacion ,string fechaLlegada,string fechaSalida)
        {
            if (reservacionCapaNegocios.verificarReservacion(new Reservacion(codigoHabitacion, fechaLlegada, fechaSalida)) > 0)
            {
                ViewBag.mensaje = "Lo sentimos, el rango de fechas que seleccionaste se encuentran ocupadas. En este calendario podrás ver que fechas se encuentran disponibles:";
                return View("Estado",reservacionCapaNegocios.sugerirReservacion());
            }
            else {
                Reservacion reservacion = new Reservacion();
                ViewData["idHabitacion"] = reservacion.codigoHabitacion;
                ViewData["fechaInicio"] = reservacion.fechaLlegada;
                ViewData["fechaFin"] = reservacion.fechaSalida;
                ViewBag.mensaje = "Habitación disponible para ser reservada";
                return View();
            }
        }

        public ActionResult GenerarReservacion(string idHabitacion, string fechaInicio, string fechaFin, string pasaporte, string nombre, string apellido, string email, string tarjeta)
        {
            Reservacion reservacion = new Reservacion();
            reservacion.codigoHabitacion = Int32.Parse(idHabitacion);
            reservacion.fechaLlegada = Convert.ToDateTime(fechaInicio);
            reservacion.fechaSalida = Convert.ToDateTime(fechaFin);

            Cliente cliente = new Cliente();
            cliente.apellido1 = apellido;
            cliente.nombre = nombre;
            cliente.pasaporte = pasaporte;
            cliente.correo = email;
            clienteCapaNegocio.registrarCliente(cliente);

            if (reservacionCapaNegocios.registrarReservacion(reservacion) == 1)
            {
                return View("Reservado");
            }
            return View("Cancelado");
        }

        public ActionResult EliminarReservacion(int reservaid)
        {

            if (reservacionCapaNegocios.eliminarReservacion(new Reservacion(reservaid)) >= 1)
            {
                ViewBag.mensaje = "Eliminado";
            }
            else
            {
                ViewBag.mensaje = "No Eliminado";
            }
            return View("ListaReservaciones", reservacionCapaNegocios.listarReservaciones());

        }
    }
}

PlayaLinda/Views/Shared/Layout_Adm.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <title>Hotel Playa Linda</title>
    <link rel="stylesheet" href="~/Content/Bootstrap.css">
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="icon" type="image/png" href="~/Content/img/hotel.svg" />




</head>

<body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="~/Content/img/hotel.svg" width="30" height="30" class="d-inline-block align-top" alt="">
            Hotel Playa Linda
        </a>
        <a class="btn btn-primary" href="/Contenido/Inicio">
            Cerrar Sesion
        </a>
    </nav>

    <br>


    <div class="wrapper">
        <nav class="shadow nav navbar-brand" syle=" background:cornflowerblue">

            <ul class="">
                <li class="nav-link">
                    @Html.ActionLink("Home", "Inicio", "Contenido")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Modificar páginas", "Nosotros", "Contenido")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Listado de reservaciones", "ListaReservaciones", "Reserva")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Administrar habitaciones", "Llegar", "Mapa")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Ver estado del hotel", "Tarifas", "Basic")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Consultar disponibilidad de habitaciones", "Reservar", "Reserva")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Publicidad", "Contacto", "Contenido")
                </li>
            </ul>
        </nav>
        @RenderBody()
    </div>
    <br>

    <footer class="page-footer" id="foote" name="foote">
        <div class="container">
            <div class="row">
                <div class="col 12 s3">
                    <h5 class="white-text" style="background-color:cornflowerblue">Contactenos</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Administracion Sitio Web</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Oficinas Centrales</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">WhatApps</a></li>
                    </ul>
                </div>
                <div class="col 12  s3">
                    <h5 class="white-text" style="background-color:cornflowerblue">Navegación</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Inicio</a></li>
                        <li><a id="ftextoA4" class="grey-text text-lighten-3" href="#!">Menu Principal</a></li>
                    </ul>

                </div>

                <div class="col 12  s3">
                    <h5 class="white-text" style="background-color:cornflowerblue">Redes Sociales</h5>
                    <ul name="texto">
                        <li>
                            <a class="grey-text text-lighten-3" href="#!">Facebook </a>
                            <i class="material-icons"></i>
                        </li>
                        <li>
                            <a class="grey-text text-lighten-3" href="#!">Twitter </a>
                            <i class="material-icons"></i>
                        </li>
                        <li>
                            <a class="grey-text text-lighten-3" href="#!">Instagram </a>
                            <i class="material-icons"></i>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div id="ftextoA15" class="container">
                © 2020 Hotel Playa Linda
                <a class="grey-text text-lighten-4 right" id="ftextoA13" href="#!">Más Información</a>
            </div>
        </div>
    </footer>


    <script src="~/Scripts/JQuery.js"></script>
    <script src="~/Scripts/Popper.js"></script>
    <script src="~/Scripts/Bootstrap.js"></script>

</body>
</html>

PlayaLinda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <title>Hotel Playa Linda</title>
    <link rel="stylesheet" href="~/Content/Bootstrap.css">
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="icon" type="image/png" href="~/Content/img/hotel.svg" />


    <script src="~/Scripts/JQuery.js"></script>


</head>

<body>
    <nav class="navbar navbar-light bg-light">

        <a class="navbar-brand" href="#">
            <img src="~/Content/img/hotel.svg" width="30" height="30" class="d-inline-block align-top" alt="">
            Hotel Playa Linda
        </a>
        <a href="/Empleado/LoginEmpleado/" class="btn btn-light">
            
           Login 
        </a>
    </nav>

    <br>


    <div class="wrapper">
        <nav class="shadow nav navbar-brand" syle=" background:cornflowerblue">

            <ul class="">
                <li class="nav-link">
                    @Html.ActionLink("Inicio", "Inicio", "Contenido")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Sobre Nosotros", "Nosotros", "Contenido")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Facilidades", "Facilidades", "Basic")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Cómo llegar", "Llegar", "Mapa")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Tarifas", "Tarifas", "Basic")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Hace reservación", "Reservar", "Reserva")
                </li>
                <li class="nav-link">
                    @Html.ActionLink("Contáctenos", "Contacto", "Contenido")
                </li>
            </ul>
        </nav>
        @RenderBody()
    </div>
    <br>

    <footer class="page-footer" id="foote" name="foote">
        <div class="container">
            <div class="row">
                <div class="col 12 s3">
                    <h5 class="white-text" style="background-color:cornflowerblue">Contactenos</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Administracion Sitio Web</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Oficinas Centrales</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">WhatApps</a></li>
                    </ul>
                </div>
                <div class="col 12  s3">
                    <h5 class="white-text" style="background-color:cornflowerblue">Navegación</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Inicio</a></li>
                        <li><a id="ftextoA4" class="grey-text text-lighten-3" href="#!">Menu Principal</a></li>
                    </ul>

                </div>

                <div class="col 12  s3">
                    <h5 class="white-text" style="background-color:cornflowerblue">Redes Sociales</h5>
                    <ul name="texto">
                        <li>
                            <a class="grey-text text-lighten-3" href="#!">Facebook </a>
                            <i class="material-icons"></i>
                        </li>
                        <li>
                            <a class="grey-text text-lighten-3" href="#!">Twitter </a>
                            <i class="material-icons"></i>
                        </li>
                        <li>
                            <a class="grey-text text-lighten-3" href="#!">Instagram </a>
                            <i class="material-icons"></i>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div id="ftextoA15" class="container">
                © 2020 Hotel Playa Linda
                <a class="grey-text text-lighten-4 right" id="ftextoA13" href="#!">Más Información</a>
            </div>
        </div>
    </footer>


    <script src="~/Scripts/Popper.js"></script>
    <script src="~/Scripts/Bootstrap.js"></script>

</body>
</html>

PlayaLinda/Views/Shared/_LayoutLogin.cshtml
@{
    ViewBag.Title = "_LayoutLogin";
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <title>Hotel Playa Linda</title>
    <link rel="stylesheet" href="~/Content/Bootstrap.css">
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="icon" type="image/png" href="~/Content/img/hotel.svg" />




</head>

<body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="~/Content/img/hotel.svg" width="30" height="30" class="d-inline-block align-top" alt="">
            Hotel Playa Linda
        </a>
    </nav>



    @RenderBody()



    <footer class="page-footer" id="foote" name="foote">
        <div class="container">
            <div class="row">
                <div class="col 12 s3">
                    <h5 class="white-text" style="background-color:cornflowerblue">Contactenos</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Administracion Sitio Web</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Oficinas Centrales</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">WhatApps</a></li>
                    </ul>
                </div>
                <div class="col 12  s3">
                    <h5 class="white-text" style="background-color:cornflowerblue">Navegación</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Inicio</a></li>
                        <li><a id="ftextoA4" class="grey-text text-lighten-3" href="#!">Menu Principal</a></li>
                    </ul>

                </div>

                <div class="col 12  s3">
                    <h5 class="white-text" style="background-color:cornflowerblue">Redes Sociales</h5>
                    <ul name="texto">
                        <li>
                            <a class="grey-text text-lighten-3" href="#!">Facebook </a>
                            <i class="material-icons"></i>
                        </li>
                        <li>
                            <a class="grey-text text-lighten-3" href="#!">Twitter </a>
                            <i class="material-icons"></i>
                        </li>
                        <li>
                            <a class="grey-text text-lighten-3" href="#!">Instagram </a>
                            <i class="material-icons"></i>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div id="ftextoA15" class="container">
                © 2020 Hotel Playa Linda
                <a class="grey-text text-lighten-4 right" id="ftextoA13" href="#!">Más Información</a>
            </div>
        </div>
    </footer>


    <script src="~/Scripts/JQuery.js"></script>
    <script src="~/Scripts/Popper.js"></script>
    <script src="~/Scripts/Bootstrap.js"></script>

</body>
</html>